### ISSUE TITLE
If RDS is lost, there will be no retuning to AF.

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#153]
When the signal drops rapidly and RDS is lost, retuning to AF will not occur, even though the entire AF list is loaded.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by Mike86-CZE** [comment]
Unfortunately, the issue still persists in today's release.

**Comment by Mike86-CZE** [comment]
Still not work in today's release. Any idea how to fix this?

**Comment by PE5PVB** [comment]
Can you check again?

**Comment by Mike86-CZE** [comment]
Good job!  Now it already works.

**Comment by Mike86-CZE** [comment]
Just a little note.  When RDS is lost, the sound changes its character, as if the tuner is constantly scanning the entire band (known from XDR-GTK), instead of only trying frequencies from the AF list.  I don't know if such behavior is okay.

**Comment by Mike86-CZE** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/cbbe8d7b-2038-4cca-8f03-46f537cd6625

**Comment by PE5PVB** [comment]
That's correct. It starts scanning all AF frequencies. I'll add 1 second delay between each search attempt.

**Comment by Mike86-CZE** [comment]
Ok, that's a good idea.
Would it be possible to have active AF retuning even when the screen is off?

**Comment by PE5PVB** [comment]
The screen on/off has no influence on AF tuning.

**Comment by Mike86-CZE** [comment]
Heard at the end of the video that it stops trying to find AF when the screen is turned off.

I am currently trying to force retune to AF using the mini transmitter.  Retuning works as long as the screen is running.  Once the screen turns off, retuning to AF stops working.

**Comment by PE5PVB** [comment]
Should not be the case. Please test.

**Comment by Mike86-CZE** [comment]
See addendum to previous comment. ⬆️

**Comment by Mike86-CZE** [comment]
The fact is that if I turn on the screen after that, all the RDS have to be reloaded.  Maybe I have something set wrong.

**Comment by Mike86-CZE** [comment]
I am now testing it in yesterday's release.  Now when RDS is lost there is no retuning at all.

**Comment by PE5PVB** [comment]
Yup. Found and fixed.

**Comment by Mike86-CZE** [comment]
> The screen on/off has no influence on AF tuning.

Retuning with the screen off doesn't work because it's probably not just the screen that's turning off, but some other components as well.  This also manifests itself, for example, with XDR-GTK connected via WiFi.  If the screen is turned off based on the screen saver setting, the TEF-PC communication will be interrupted.

**Comment by PE5PVB** [comment]
Ah, now I understand what goes wrong. Should be fixed. Please check and report.

**Comment by Mike86-CZE** [comment]
Unfortunately.  Retuning still doesn't work after turning off the screen.

**Comment by PE5PVB** [comment]
Ah, my mistake.

**Comment by Mike86-CZE** [comment]
Is AF selection dependent on signal strength? I have a station tuned in, the AF list is loaded. The signal intensity is 43 dBμV. I start the transmitter on the same frequency and the intensity increases to 58 dBμV. I can hear the tuner trying to search for AF, but it won't switch to one. However, such a situation probably does not occur often in normal practice.

**Comment by PE5PVB** [comment]
Yes but noise and multi-path has more weight in scoring the AF

**Comment by Mike86-CZE** [comment]
I observed that retuning occurs only when the intensity of the interfering signal drops below approximately 50 dBμV.

**Comment by Mike86-CZE** [comment]
It can be said that it is already working well.  After the screen turns off, it still searches for AF even when RDS is lost.  However, if I turn on the screen and there is currently no RDS reception, the AF list is lost and the search does not occur until the AFs are reloaded from RDS.

**Comment by PE5PVB** [comment]
I don't understand what you mean. Why RDS reception gets lost after turning on the screen?

**Comment by Mike86-CZE** [comment]
RDS reception was lost earlier due to signal drop.  But TEF still knew AF and was trying to find them.  However, when the screen is turned back on, the TEF forgets the AF list and therefore no longer searches for AFs until they are reloaded from the RDS.

**Comment by PE5PVB** [comment]
Should be fixed now.

**Comment by Mike86-CZE** [comment]
Ok, fixed.  I would just maybe increase the AF search interval to about 5 seconds after several unsuccessful attempts to retune.  Constantly searching for AF after 1 second for a long time feels uncomfortable.

**Comment by PE5PVB** [comment]
That should already be the case.

**Comment by Mike86-CZE** [comment]
Unfortunately, I have to reopen this issue.  Strange AF retuning behavior after screen off.  In some situations, after turning off the screen, retuning stops working completely.  Other times, after turning off the screen, on the contrary, it tries to retune (but does not retune), even if there is no reason to do so (the signal is good).  After turning on the screen, everything is fine again.

**Comment by PE5PVB** [comment]
Ah, found it. Please test again

**Comment by Mike86-CZE** [comment]
Now it's fine.  As for the extended AF search interval after several failed attempts, it doesn't seem to be implemented yet.  Even after a long time, he still tries every second.

**Comment by PE5PVB** [comment]
What do you mean by that?

Currently AF is triggered when:
1. On RDS loss (1 sec. delay)
2. When signal is very disturbed (1 sec. delay)
3. When signal has little noise (10 sec. delay)

Ofcourse some RDS data should be processed first, otherwise there are no AF frequencies to test. So when tuning into a bad signal it's possible AF won't work directly.

**Comment by Mike86-CZE** [comment]
Ah, thanks for the detailed description of AF behavior.  In that case, it would probably be enough to increase the AF search interval when RDS is lost, perhaps to 5 seconds?

**Comment by PE5PVB** [comment]
Correct, and that is the way how it should work. It's designed for mobile use. When you are moving closer to another transmitter it will switch. If you should disable it after a few unsuccesfull attempts you will finaly loose reception.

**Comment by Mike86-CZE** [comment]
My point is that not every station has such a dense network of transmitters that flawless reception with RDS from at least one transmitter is always available.  If I'm in an area with no RDS reception for an extended period of time, but the sound quality is still pretty good, frequent AF searches are annoying because every attempt to retune is audible.  Currently, this happens every second when losing RDS (but still good sound reproduction), which is annoying.

**Comment by PE5PVB** [comment]
Well, it's just a disadvance of a single tuner. I close this issue.

**Comment by Mike86-CZE** [comment]
With a single-tuner receiver, this can of course only be solved by some kind of compromise.  Which I think the five second interval in case of RDS loss would be.  Anyway, thank you for your excellent work.
