### ISSUE TITLE
Stationlist for Android just one direction on direct connections

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#157]
Seems TEF does not tell Stationlist for Android a changed frequency.

The other way round works, Stationlist for Android controls the TEF.

**Comment by PE5PVB** [comment]
Does it work when you use XDRGTK?

**Comment by andimik** [comment]
Yes, it does. This was my backup solution as I am currently on a mountain for DXing. But this is PC related of course.

**Comment by andimik** [comment]
Can you check if `serial.print` within `if` lines are ever used now?

**Comment by PE5PVB** [comment]
Communication to Stationlist is udp traffic, not serial. Do you know a website were communication with the android app is explained?

**Comment by andimik** [comment]
Oh, let me then check UDP payload.

**Comment by andimik** [comment]
https://dx.3sdesign.de/index.htm?simple_radio_control_protocol.htm

Thanks to a hint of the author I got this link regarding the UDP commands.

He also told me, he expects bi-directional traffic and interactive usage.

**Comment by PE5PVB** [comment]
Yes, I used these commands to communicate with Stationlist. Maybe your phone's firewall is blocking something?

**Comment by andimik** [comment]
> Does it work when you use XDRGTK?

I fear I did not understand you correctly last week, seems you asked if *Stationlist* via *xdr-gtk* works. I need to try that (see below, with success :-) ).

My answer last week was regarding if *xdr-gtk* works in general.

Today I have tested the first ever 2.00 from 16th June and *Stationlist for Android* (direct connected to TEF via WiFi) is still one direction. Seems this has never worked so far.

But thanks to your question (which I initially understood wrong), **I confirm that *Stationlist for Android* works bi-directional, **when** it's connected to *xdr-gtk*.**

So it's **only broken using direct connection** (when you are **not** able to use your mobile **and** your laptop).

**Comment by PE5PVB** [comment]
I changed one thing, the indentification had a space in it, I removed this one, maybe the Android app can't handle this. Please test again with a next beta release.

**Comment by andimik** [comment]
Let me guess before I wait for your commit. 

You have replaced the space in `TEF Tuner`.

If yes, then that won't solve the issue.

**Comment by andimik** [comment]
I've checked the UDP payload 

# direct from TEF

[stationlist_tef.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12264568/stationlist_tef.zip)

# via xdr-gtk

[stationlist_xdrgtk.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12264600/stationlist_xdrgtk.zip)

Is there a difference?

Maybe yes, in the direct connection there are some malformed packets from AF list.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e3247681-c640-499c-8750-8c76cfce77e4)

**Comment by PE5PVB** [comment]
When I open the log from xdrgtk, I still see the log from the TEF tuner?

**Comment by andimik** [comment]
[stationlist_xdrgtk_v2.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12264716/stationlist_xdrgtk_v2.zip)

This is now hopefully the right udp packet *Wireshark* capture. You see

```
from=XDR-GTK;RcvLevel=61from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=62from=XDR-GTK;RcvLevel=61from=XDR-GTK;RcvLevel=61from=XDR-GTK;RcvLevel=61;bandwidth=-1;freq=99000000from=XDR-GTK;RcvLevel=23;bandwidth=-1;freq=98600000from=XDR-GTK;RcvLevel=20;bandwidth=-1;freq=98400000from=XDR-GTK;RcvLevel=22from=XDR-GTK;RcvLevel=24;bandwidth=-1;freq=98300000from=XDR-GTK;RcvLevel=22
``` 

and the frequency changes from SL for Android

```
from=StationList;freq=99000000from=StationList;freq=98900000from=StationList;freq=98800000from=StationList;freq=98700000from=StationList;freq=98600000from=StationList;freq=98500000from=StationList;freq=98400000from=StationList;freq=98300000from=StationList;freq=98100000from=StationList;freq=98000000from=StationList;freq=97900000from=StationList;freq=97800000from=StationList;freq=97700000from=StationList;freq=97600000from=StationList;freq=97500000from=StationList;freq=97400000from=StationList;freq=97300000from=StationList;freq=97200000from=StationList;freq=97100000from=StationList;freq=97000000from=StationList;freq=96900000from=StationList;freq=96800000from=StationList;freq=96700000from=StationList;freq=96600000from=StationList;freq=96500000from=StationList;freq=96400000from=StationList;freq=96300000from=StationList;freq=96200000from=StationList;freq=96100000from=StationList;freq=96000000from=StationList;freq=95900000from=StationList;freq=95800000from=StationList;freq=98700000from=StationList;freq=98500000from=StationList;freq=98600000from=StationList;freq=98700000from=StationList;freq=98800000from=StationList;freq=98900000from=StationList;freq=99000000from=StationList;freq=99100000
```

**Comment by PE5PVB** [comment]
OK. Looks like XDRGTK is not sending a RDSclear command. I removed this from my build as well, can you check if it works now?

**Comment by andimik** [comment]
This was also my idea, but that did not help.

Tested with a0e63c701d.

BTW: Please don't use the main branch for testing ...

**Comment by PE5PVB** [comment]
OK. I did some more optimising. I will release a beta with todays changes. Maybe it works now.

**Comment by andimik** [comment]
Will try in the evening.

**Comment by andimik** [comment]
Unfortunately, it did not work and I guess I know the reason. 

**TEF_tuner does not transmit the frequency, only Bandwidth and RcvLevel**!

Seems the lines
https://github.com/PE5PVB/TEF6686_ESP32/blob/dac2b6fadf95ec6c8d46775bd23e90328682e378/TEF6686_ESP32.ino#L2903-L2906 
are not transmitted at all! Please see `Bandwidth` in capital letters, which comes from https://github.com/PE5PVB/TEF6686_ESP32/blob/dac2b6fadf95ec6c8d46775bd23e90328682e378/TEF6686_ESP32.ino#L3131

And RcvLevel comes from https://github.com/PE5PVB/TEF6686_ESP32/blob/dac2b6fadf95ec6c8d46775bd23e90328682e378/TEF6686_ESP32.ino#L2980

I've installed a pcap app in Android and made the following captures.

# Direct via TEF and Stationlist for Android

```
from=StationList;freq=?
from=TEF_tuner;RcvLevel=17
from=StationList;freq=95900000
from=StationList;freq=96500000
from=StationList;freq=97700000
from=StationList;freq=98400000
from=StationList;freq=99000000
from=TEF_tuner;RcvLevel=17
from=StationList;freq=99700000
from=StationList;freq=100300000
from=StationList;freq=100500000
from=TEF_tuner;RcvLevel=19
from=TEF_tuner;RcvLevel=19
from=TEF_tuner;RcvLevel=19
from=TEF_tuner;RcvLevel=19
from=TEF_tuner;Bandwidth=56000
from=TEF_tuner;RcvLevel=20
from=StationList;freq=100400000
from=StationList;freq=100200000
from=StationList;freq=99700000
from=StationList;freq=99300000
from=StationList;freq=98900000
from=StationList;freq=98400000
from=StationList;freq=98000000
from=StationList;freq=97900000
from=TEF_tuner;RcvLevel=46
from=TEF_tuner;RcvLevel=43
from=TEF_tuner;RcvLevel=40
from=TEF_tuner;Bandwidth=114000
from=TEF_tuner;RcvLevel=36
from=TEF_tuner;RcvLevel=35
from=StationList;freq=98100000
from=StationList;freq=98400000
from=StationList;freq=99300000
from=StationList;freq=99700000
from=StationList;freq=100100000
from=StationList;freq=100400000
from=StationList;freq=100600000
from=StationList;freq=100700000
from=StationList;freq=100800000
from=TEF_tuner;RcvLevel=20
from=TEF_tuner;RcvLevel=20
from=TEF_tuner;Bandwidth=114000
from=TEF_tuner;RcvLevel=20
from=TEF_tuner;RcvLevel=20
from=TEF_tuner;RcvLevel=23
from=TEF_tuner;RcvLevel=23
from=StationList;freq=100700000
from=StationList;freq=100500000
from=StationList;freq=99600000
from=StationList;freq=98400000
from=TEF_tuner;RcvLevel=11
from=StationList;freq=98000000
from=StationList;freq=97700000
from=StationList;freq=97500000
from=TEF_tuner;RcvLevel=12
from=TEF_tuner;RcvLevel=13
from=TEF_tuner;RcvLevel=13
from=TEF_tuner;RcvLevel=14
from=TEF_tuner;Bandwidth=114000
from=TEF_tuner;RcvLevel=15
from=StationList;freq=97600000
from=TEF_tuner;RcvLevel=24
from=StationList;freq=97700000
from=TEF_tuner;RcvLevel=22
from=StationList;freq=97800000
from=TEF_tuner;RcvLevel=22
from=StationList;freq=97900000
from=TEF_tuner;RcvLevel=44
from=StationList;freq=98000000
from=TEF_tuner;RcvLevel=36
from=StationList;freq=98100000
from=TEF_tuner;RcvLevel=30
```
(I've made a new line here in Github)

[PCAPdroid_05_Aug._18_.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12267761/PCAPdroid_05_Aug._18_.zip)
[laptop_xdrgtk.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12267762/laptop_xdrgtk.zip)
[PCAPdroid_05_Aug._18_38_43.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12267763/PCAPdroid_05_Aug._18_38_43.zip)

[PCAPdroid_05_Aug._19_27_39.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12267777/PCAPdroid_05_Aug._19_27_39.zip)

[PCAPdroid_05_Aug._19_48_51.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12267801/PCAPdroid_05_Aug._19_48_51.zip)

Well, I've changed the lines to 

```
  if (wifi) {
    Udp.beginPacket(remoteip, 9030);
    Udp.print("from=TEF_tuner;RcvLevel=");
    Udp.print(String(SStatus / 10));
    Udp.print("from=TEF_tuner;freq=");
      if (band > BAND_GAP) {
        Udp.print(String(frequency_AM) + "000");
      } else {
        Udp.print(String(band == BAND_FM ? frequency : frequency_OIRT) + "0000");
      }
    Udp.endPacket();
  }
```

So at least the frequency is transmitted, but it seems that also other parameters are needed for *Stationlist for Android*

```

from=StationList;freq=?
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;freq=100100000
from=StationList;freq=?
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;freq=100100000
from=StationList;freq=100200000
from=StationList;freq=100400000
from=StationList;freq=101400000
from=StationList;freq=101900000
from=StationList;freq=102300000
from=StationList;freq=102700000
from=StationList;freq=102900000
from=StationList;freq=103100000
from=StationList;freq=103200000
from=StationList;freq=103300000
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;freq=100100000
from=TEF_tuner;Bandwidth=64000
from=TEF_tuner;RcvLevel=46
from=TEF_tuner;freq=100400000
from=TEF_tuner;RcvLevel=43
from=TEF_tuner;freq=101400000
from=TEF_tuner;RcvLevel=42
from=TEF_tuner;freq=101900000
from=TEF_tuner;RcvLevel=40
from=TEF_tuner;freq=102300000
from=StationList;freq=103400000
from=TEF_tuner;RcvLevel=51
from=TEF_tuner;freq=104000000
from=StationList;freq=103500000
from=TEF_tuner;RcvLevel=15
from=TEF_tuner;freq=103400000
from=StationList;freq=103000000
from=TEF_tuner;RcvLevel=46
from=TEF_tuner;freq=104000000
from=StationList;freq=102500000
from=TEF_tuner;RcvLevel=21
from=TEF_tuner;freq=103000000
from=StationList;freq=102000000
from=TEF_tuner;RcvLevel=24
from=TEF_tuner;freq=102500000
from=StationList;freq=101500000
from=TEF_tuner;RcvLevel=15
from=TEF_tuner;freq=102000000
```

[PCAPdroid_05_Aug._20_07_29.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12267879/PCAPdroid_05_Aug._20_07_29.zip)

**Comment by PE5PVB** [comment]
Frequency is send when frequency is changed. This works fine with Stationlist on PC.

**Comment by andimik** [comment]
Indeed. I have captured that when connected to Stationlist for Windows (running under Wine and Ubuntu).

[tef_stationlist_windows_short.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12269941/tef_stationlist_windows_short.zip)
[tef_stationlist_windows.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12269942/tef_stationlist_windows.zip)


```
from=StationList;freq=102900000
```

```

from=TEF_tuner;RT1=4d555241545f265f4a4f53455f464541542e5f4d4159415f2d5f504f5354414e5f54495f53414d008000000039a73900c0c1403f40bd0f40f4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RT1=4d555241545f265f4a4f53455f464541542e5f4d4159415f2d5f504f5354414e5f54495f53414d001448fc3fcc46fc3fc6250000000000fff4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RT1=4d555241545f265f4a4f53455f464541542e5f4d4159415f2d5f504f5354414e5f54495f53414d008000000039a73900c0c1403f40bd0f40f4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RT1=4d555241545f265f4a4f53455f464541542e5f4d4159415f2d5f504f5354414e5f54495f53414d008000000039a73900c0c1403f40bd0f40f4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RcvLevel=52;bandwidth=-1;freq=102900000
from=TEF_tuner;PTY=20
from=TEF_tuner;RT1=00000000fffffffff4aa0d8040dbfc3f9c58fc3fb7d4a2145f210000100000001a0000000100008093d80000349f4a3fc0a82bfc000000000000000000000000
from=TEF_tuner;PI=....
from=TEF_tuner;PS=0000000000c0a82b
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RT1=00c2403f40bd0f40fb9d0d805fdbfc3f3457fc3f0100000038000000040000001a000000000000800050f63f050000002300000016000000f4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=52
from=TEF_tuner;RT1=007efb3f00000000fb9d0d805fdbfc3f3457fc3f0100000038000000040000001a00000001000080b7d4a2146461fc3f744bfc3f764bfc3ff4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=53
from=TEF_tuner;RT1=007efb3f00000000fb9d0d805fdbfc3f3457fc3f0100000038000000040000001a000000010000808000000039a73900c0c1403f40bd0f40f4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=53
from=TEF_tuner;RT1=007efb3f00000000fb9d0d805fdbfc3f3457fc3f0100000038000000040000001a000000000000808000000039a73900c0c1403f40bd0f40f4aa0d8040dbfc3f
from=TEF_tuner;RcvLevel=53
from=TEF_tuner;RT1=00000000f8000000fb9d0d805fdbfc3f3457fc3f0100000038000000040000001a00000001000080b7d4a2146461fc3f000000008cdafc3ff4aa0d8040dbfc3f
from=TEF_tuner;PI=A213
from=TEF_tuner;RcvLevel=53
from=TEF_tuner;RT1=00000000a058fc3ffb9d0d805fdbfc3f3457fc3f0100000038000000040000001a00000001000080b7d4a2146461fc3f0100000060dafc3ff4aa0d8040dbfc3f
```

And then back on Android, no frequency, no AF

```
from=TEF_tuner;RcvLevel=36
from=TEF_tuner;RcvLevel=10
from=TEF_tuner;RcvLevel=13
from=TEF_tuner;RcvLevel=13
from=TEF_tuner;RcvLevel=35
from=TEF_tuner;RcvLevel=7
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;Bandwidth=64000
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=8
from=TEF_tuner;RcvLevel=9
```

**Sjef, there is a bug indeed. If connected to *Stationlist for Android* another script from the sources are used!** See above, I already told you the lines.

Please see the word `bandwidth` resp. `Bandwidth`, it's not the same.

# TEF sends to Stationlist for Windows 

`from=TEF_tuner;RcvLevel=52;bandwidth=-1;freq=102900000` 

# TEF sends to Stationlist for Android

`from=TEF_tuner;Bandwidth=64000`

**Comment by andimik** [comment]
Progress!

Now TEF transmits the frequency, but SL for Android still does not want to update to the new frequency.

```
from=StationList;freq=102900000
from=TEF_tuner;RcvLevel=59;bandwidth=-1;freq=99100000
from=TEF_tuner;PI=A3DD
from=TEF_tuner;PTY=3
from=TEF_tuner;PS=5355445449524f4c
from=StationList;freq=103000000
from=TEF_tuner;RcvLevel=56;bandwidth=-1;freq=102900000
from=TEF_tuner;PI=A213
from=TEF_tuner;PTY=0
from=TEF_tuner;PS=5f5f464d345f5f5f
from=StationList;freq=103100000
from=TEF_tuner;RcvLevel=25;bandwidth=-1;freq=103000000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=103200000
from=TEF_tuner;RcvLevel=13;bandwidth=-1;freq=103100000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=103300000
from=TEF_tuner;RcvLevel=8;bandwidth=-1;freq=103200000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=103400000
from=TEF_tuner;RcvLevel=9;bandwidth=-1;freq=103300000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=105200000
from=TEF_tuner;RcvLevel=48;bandwidth=-1;freq=105500000
from=TEF_tuner;PI=A550
from=TEF_tuner;PTY=0
from=TEF_tuner;PS=5f5f41474f52415ffrom=StationList;freq=104000000
from=TEF_tuner;RcvLevel=23;bandwidth=-1;freq=105200000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=102500000
from=TEF_tuner;RcvLevel=52;bandwidth=-1;freq=104000000
from=TEF_tuner;PI=9202
from=TEF_tuner;PTY=9
from=TEF_tuner;PS=56414c5f3230325f
from=StationList;freq=105500000
from=TEF_tuner;RcvLevel=25;bandwidth=-1;freq=102500000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
```

https://github.com/PE5PVB/TEF6686_ESP32/blob/dac2b6fadf95ec6c8d46775bd23e90328682e378/TEF6686_ESP32.ino#L2978-L2983 and following should be

```
  if (wifi) {    // for Stationlist for Android modified by andimik
    Udp.beginPacket(remoteip, 9030);
    Udp.print("\nfrom=TEF_tuner;RcvLevel=");
    Udp.print(String(SStatus / 10));
    Udp.print(";bandwidth=-1;freq=");
      if (band > BAND_GAP) {
        Udp.print(String(frequency_AM) + "000");
      } else {
        Udp.print(String(band == BAND_FM ? frequency : frequency_OIRT) + "0000");
      }
    Udp.print("\nfrom=TEF_tuner;PI=" + String(radio.rds.picode, 4));
    Udp.print("\nfrom=TEF_tuner;PTY=");
    Udp.print(String(radio.rds.stationTypeCode, HEX));
          Udp.print("\nfrom=TEF_tuner;PS=");
      char PShex[9];
      radio.rds.stationName.toCharArray(PShex, 9);
      for (int i = 0; i < 8; i++)
      {
        if (PShex[i] < 0x10) Udp.print("0");
        if (PShex[i] == 0x20) PShex[i] =  '_';
        Udp.print(String(PShex[i], HEX));
      }
    Udp.endPacket();
  }
```

But then we have the same code again in the source code ...

**Comment by PE5PVB** [comment]
So with a leading \n it works?

**Comment by andimik** [comment]
No, I tried that just for better formatting, but no influence.

Well, it does not work, but the texts are being transmitted.

```

from=StationList;freq=105700000
from=TEF_tuner;RcvLevel=20;freq=88300000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=105800000
from=TEF_tuner;RcvLevel=6;freq=105700000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=105900000
from=TEF_tuner;RcvLevel=5;freq=105800000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=106000000
from=TEF_tuner;RcvLevel=16;freq=105900000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
from=StationList;freq=104900000
from=TEF_tuner;RcvLevel=36;freq=87600000
from=TEF_tuner;PI=51CC
from=TEF_tuner;PTY=7
from=TEF_tuner;PS=522e4d415249415f
from=StationList;freq=105500000
from=TEF_tuner;RcvLevel=57;freq=104900000
from=TEF_tuner;PI=A540
from=TEF_tuner;PTY=a
from=TEF_tuner;PS=414e54454e4e455f
```

Maybe I need to investigate, why the IP-Address is different.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/efae1fb7-3eba-4846-b84c-a2941cdd980c)

I am expecting my mobile phone as 192.168.43.1, not as 10.215.173.1.

**Comment by andimik** [comment]
testing 77e8596

Do you expect anything new in 2495ff as you have just changed from uppercase `Udp.print("from=TEF_tuner;Bandwidth=");` to lowercase `Udp.print("from=TEF_tuner;bandwidth=");`? 

This has no influence on Stationlist for Android.

```
from=StationList;freq=105900000
from=TEF_tuner;RcvLevel=58
from=StationList;freq=106000000
from=TEF_tuner;RcvLevel=16
from=StationList;freq=104000000
from=TEF_tuner;RcvLevel=38
from=StationList;freq=105500000
from=TEF_tuner;RcvLevel=51
from=StationList;freq=104500000
from=StationList;freq=104500000
from=StationList;freq=104900000
from=StationList;freq=104000000
from=StationList;freq=106700000
from=TEF_tuner;RcvLevel=42
from=TEF_tuner;RcvLevel=43
from=TEF_tuner;RcvLevel=44
from=TEF_tuner;RcvLevel=45
from=TEF_tuner;RcvLevel=45
from=StationList;freq=106800000
from=TEF_tuner;RcvLevel=23
from=StationList;freq=105200000
from=TEF_tuner;RcvLevel=15
from=StationList;freq=105300000
from=TEF_tuner;RcvLevel=22
```

In order to achieve better communication with SL for Android, you need to modify the other code mentioned above, which is now in L2342ff (= inside of `void ShowSignalLevel()`)

**Comment by PE5PVB** [comment]
Can you make an example what you want to happen? It's just plain UDP traffic.

**Comment by andimik** [comment]
Yes, I am aware what UDP traffic is, but there are two (2) different codes for UDP traffic at the moment, which I find quite useless.

One is for **SL for Windows** (which you have shifted to `rds.cpp`, lines 650, 663, 683, 745), the other is for **SL for Android** (still in the ino-file)

See above, currently there is **no** frequency information transmitted over UDP for **SL for Android**.

In order to update the frequency on **SL for Android** TEF should transmit at least the frequency, but it doesn't.

Please see my patch above, it will transmit the correct info even for **SL for Android**, but I still need to test the communication.

**Comment by PE5PVB** [comment]
Well, there is no detection of any connection, so the UDP packets are always transmitted when WiFi is connected, even when you don't run stationlist on any device at all.

**Comment by andimik** [comment]
Are you sure?

**Comment by PE5PVB** [comment]
Yup. Try it.

**Comment by PE5PVB** [comment]
When you change frequency it will send UDP packets. Every time when a new frequency is shown on the display and wifi is enabled it will run this:
    if (wifi) {
      String stationprint;
      stationprint = "from=TEF_tuner;RcvLevel=";
      stationprint += String(SStatus / 10);
      stationprint += ";bandwidth=-1;freq=";
      if (band > BAND_GAP) {
        stationprint += String(frequency_AM) + "000";
      } else {
        stationprint += String(band == BAND_FM ? frequency : frequency_OIRT) + "0000";
      }
      Udp.beginPacket(remoteip, 9030);
      Udp.print(stationprint);
      Udp.endPacket();
    }

**Comment by PE5PVB** [comment]
Make sure your Stationlist is listening to port 9030

**Comment by andimik** [comment]
> Make sure your Stationlist is listening to port 9030

Of course it does. I cannot change that in the tool ("SL listens to Port -1"), it's hardcoded.

I tried several times, when I connect my mobile I get other results than when I connect my PC.

Modifying L2352 with 

```
  if (wifi) {
 // for Stationlist for Android modified by andimik
    Udp.beginPacket(remoteip, 9030);
    Udp.print("\nfrom=TEF_tuner;RcvLevel=");
    Udp.print(String(SStatus / 10));
    Udp.print(";bandwidth=-1;freq=");
      if (band > BAND_GAP) {
        Udp.print(String(frequency_AM) + "000");
      } else {
        Udp.print(String(band == BAND_FM ? frequency : frequency_OIRT) + "0000");
      }
    Udp.print("\nfrom=TEF_tuner;PI=" + String(radio.rds.picode, 4));
    Udp.print("\nfrom=TEF_tuner;PTY=");
    Udp.print(String(radio.rds.stationTypeCode, HEX));
          Udp.print("\nfrom=TEF_tuner;PS=");
      char PShex[9];
      radio.rds.stationName.toCharArray(PShex, 9);
      for (int i = 0; i < 8; i++)
      {
        if (PShex[i] < 0x10) Udp.print("0");
        if (PShex[i] == 0x20) PShex[i] =  '_';
        Udp.print(String(PShex[i], HEX));
      }
    Udp.endPacket();
  }
```

will transmit the frequency!!!

> Every time when a new frequency is shown on the display and wifi is enabled it will run this:

No it does not!

**Comment by PE5PVB** [comment]
Please tell me what your script does. I'm a bit confused now.

**Comment by andimik** [comment]
It's **your** script just copied to another location.

**Comment by andimik** [comment]
forget `\n`, this is just cosmetic.

**Comment by PE5PVB** [comment]
But how are you sure it's not transmitted to your phone? How do you log this?

**Comment by andimik** [comment]
Please see above, I've recorded some pcap files for that reason, the capture is done on the **same** device (mobile resp. laptop), where Stationlist is running (Android resp. Windows).

The UDP packets are **not** the same for SL for Windows and SL for Android.

I've realized that because you made a different spelling in the word "bandwidth" by chance.

Captured with modified code from above on the **right** place in the source code.

[PCAPdroid_07_Aug._23_38_58.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12285441/PCAPdroid_07_Aug._23_38_58.zip)

```
from=StationList;freq=104800000
from=TEF_tuner;RcvLevel=44;bandwidth=-1;freq=105500000
from=TEF_tuner;PI=A550
from=TEF_tuner;PTY=0
from=TEF_tuner;PS=5f5f41474f52415ffrom=StationList;freq=104900000
from=TEF_tuner;RcvLevel=22;bandwidth=-1;freq=104800000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000from=StationList;freq=?
from=TEF_tuner;RcvLevel=53;bandwidth=-1;freq=106000000
from=TEF_tuner;PI=9203
from=TEF_tuner;PTY=0
from=TEF_tuner;PS=5f5f4152535f5f5ffrom=StationList;freq=105000000
from=TEF_tuner;RcvLevel=53;bandwidth=-1;freq=106000000
from=TEF_tuner;PI=9203
from=TEF_tuner;PTY=0
from=TEF_tuner;PS=5f5f4152535f5f5ffrom=StationList;freq=105100000
from=TEF_tuner;RcvLevel=13;bandwidth=-1;freq=105000000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000from=StationList;freq=105200000
from=TEF_tuner;RcvLevel=7;bandwidth=-1;freq=105100000
from=TEF_tuner;PI=....
from=TEF_tuner;PTY=20
from=TEF_tuner;PS=0000000000000000
```

Without this modification you will never see a frequency from TEF_tuner.

**Comment by andimik** [comment]
In the meantime I had contact with the author of Stationlist. He gave me a hint, and I will test that in the next days.

So no further need to investigate here at the moment.

**Comment by andimik** [comment]
I'll give up, sorry. There is definitely a bug, but I cannot tell you if the problem is on **TEF6686** side or even on **Stationlist-M** side.

Could you test it on your mobile please?

I've tried my mobile and an Android tablet, same result.

Fact is: TEF will NOT transmit the frequency when you change the frequency on TEF.

Please do **not** test it in Stationlist for Windows. Here it works.

> When you change frequency it will send UDP packets. Every time when a new frequency is shown on the display and wifi is enabled it will run this:

Are you sure? I do **not** see that. During this capture, I was changing the frequency on the TEF quite often. There is nothing in the pcap-file.

```
from=StationList;freq=87600000
from=TEF_tuner;RcvLevel=33
from=StationList;freq=87700000
from=TEF_tuner;RcvLevel=37
from=StationList;freq=87800000
from=TEF_tuner;RcvLevel=19
from=StationList;freq=87900000
from=TEF_tuner;RcvLevel=13
from=StationList;freq=?
from=TEF_tuner;RcvLevel=47
from=StationList;freq=?
from=TEF_tuner;RcvLevel=47
```

[PCAPdroid_14_Aug._12_17_07.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12333848/PCAPdroid_14_Aug._12_17_07.zip)

**Comment by PE5PVB** [comment]
I checked again, the only time that it was not transmitted over UDP was when screenmute was on. I fixed that, even when I now set the destination address to my doorbell, UDP packets are send.

**Comment by andimik** [comment]
I have never used screenmute.

Have you tried that?

**Comment by PE5PVB** [comment]
No, but again, I checked. Now it always transmits the UDP packet to the destination device. I tested it with portmapping and send it to my doorbell, my router and my kids toy. So if your phone is still not receiving it, it means your phone's firewall is filtering it. I have to make a few small changes and upload the new version.

**Comment by andimik** [comment]
Remark:

https://github.com/kkonradpl/xdr-gtk/blob/616d5015dc1f49aec76d4fc70e654112b7f20378/src/conf-defaults.h#L87-L97

`xdr-gtk` **only** uses the port, but **no** IP address can be set in the program. And it **works** with *SL-M*. 

The author of *Stationlist* gave me the hint that *TEF* should answer to **that** IP address where the question came from.

He told that TEF might use a **wrong** IP address as my pcap files do not show all the UDP packets which we expect.

In the meantime I have tested three Android devices. Same result.

The only thing I could try is to use another network (with a WiFi router). But then you can only use it at home and you won't need the Android version ...

Because up to now the Android mobile is creating a hotspot (192.168.43.1).

Another idea: Is the value for `remoteip` always ok in each line of the ino file? I could try to replace the variable with hard-coded `192.168.43.1` and see what happens then ...

**Comment by Overland-DX** [comment]
It works on my phone when I set the phone's ip address in the tef6686 radio. And I changed Stationlist ID 1.

**Comment by andimik** [comment]
@mx4zxc

When you change the frequency on the TEF, will it change on Stationlist-M as well?

Do you use Hotspot or another network?

**Comment by Overland-DX** [comment]
Yes, it works well both in the home network and when I use the phone as a hotspot. But there is a small bug. When I tune with tef and switch to tuning with the app, the app does not update when I tune again with tef. Then I have to go into the settings and change the station list ID to another number... after that the app updates when I tune with tef again. Attached are some pictures of my setup.
![Screenshot_20230815_101203](https://github.com/PE5PVB/TEF6686_ESP32/assets/102610897/d3ec3ba6-eebb-44bb-a328-8b4256ad1afc)
![20230815_101323](https://github.com/PE5PVB/TEF6686_ESP32/assets/102610897/46decbcc-03b0-442a-b297-336e2d40c032)

**Comment by Overland-DX** [comment]
I really hope you get around to this, because it's a very useful tool. Thank you very much for sharing the link and information with me.

**Comment by andimik** [comment]
> But there is a small bug. When I tune with tef and switch to tuning with the app, the app does not update when I tune again with tef.

This is exactly the same bug I'm talking about all the time in this issue.

MANY THANKS for confirming that, too.

**Comment by Overland-DX** [comment]
I'm so sorry, I misunderstood your problem. I thought you meant that tef never updated the correct frequency to the app when tuning with tef. Which it actually does.

**Comment by andimik** [comment]
The next days I will test hardcoding the IP address, if this works, I will send the value of `remoteip` for each line in the code to the mobile and check if it is NULL or even a wrong IP.

**Comment by Overland-DX** [comment]
@andimik It is good. Hope you figure it out. Anyway, I'm very glad that you made me aware of this app. It will be used a lot in the future :)

**Comment by andimik** [comment]
And I will try `socat` on the terminal of my (not rooted mobile)

https://android.stackexchange.com/questions/168422/how-to-port-forward-internet-using-android-hotspot-to-pc

**Comment by Overland-DX** [comment]
I have put the phone in hotspot mode and connected my tef6686 to the phone via WIFI.
1. Open the app JB's StationList-M(SL-M).
2. Change frequency with tef6686 and the new frequency is updated in the SL-M app.
3. Change the frequency in SL-M and the tef6686 automatically changes the frequency to the one I set in the SL-M app.
4. Change the frequency again with the tef6686, but this time the SL-M app is not updated with the new frequency that I set in the tef6686.
5. Hold down the mode button to enter the menu, then immediately press mode and exit the menu.
6. Change frequency with the tef6686 radio and the SL-M app is updated with the new frequency.

It seems that there is a two-way connection, but that the tef6686 does not automatically update the SL-M after you change the frequency with the SL-M app.
But it's enough to go into the menu and out again, then it starts sending the frequency change again.

Just tested holding the "band"(Advanced RDS) button and it started sending frequency changes to the SL-M app again.

**Comment by PE5PVB** [comment]
TEF writes data to port 9030 and listens to 9031. This is how the PC version of Stationlist works.

**Comment by Overland-DX** [comment]
Yes, it seems very nice. Here I use the phone as a mobile Wi-Fi zone (hotspot):
https://youtu.be/Rzp4MHQUpw8

**Comment by andimik** [comment]
Interesting. It works in your case. Which firmware and date (resp. commit) is that?

According to the new frequency font it is the latest, right?

**Comment by Overland-DX** [comment]
Yes, it is the latest version. I have not tested with other versions. I think it is important that the StationList IP in the tef6686 is set to the ip address of your phone. and in JB's StationList-M listens to the IP address of Tef6686 with default port 9031. That's probably the only thing I did in the settings, and it worked right away.

**Comment by andimik** [comment]
That's the way I am doing as well of course.

In the next days (when Sjef is on vacation) I will try to investigate why I only get fragments on the phone.

**Comment by andimik** [comment]
Sjef, your latest changings in the code seem that you forgot that the UDP packet codes have two (2) sources.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/20eec737-eccb-4a34-aa75-7371f8e17d35)

That's what I am talking about all the time. The same code is used at least another time ...

**Comment by andimik** [comment]
In the meantime I found a device where it worked **until** I changed the frequency in SL-M. Then I had the same problem again and SL-M was not updated when TEF tunes its frequency. But the name was `TEF_tuner` all the time.

Then I changed the device and the name was `TEF_tuner 1` and it didn't work
Maybe it has to do if you tune to a RDS frequency or not.

As there is another bug in RDS I will send a Pull request ananyw

@mx4zxc

Can you please tell me, what is shown in Stationlist-M server name? `TEF_tuner 1` or just `TEF_tuner` (without space and number).

**Comment by Overland-DX** [comment]
@andimik 
It doesn't matter which ID I choose. It works anyway.
![3xdevice_id](https://github.com/PE5PVB/TEF6686_ESP32/assets/102610897/6389ad2d-3346-4879-9aef-f1b171c6585c)
In this part:
"In the meantime I found a device where it worked until I changed the frequency in SL-M. Then I had the same problem again and SL-M was not updated when TEF tunes its frequency."
Did you just try to go in to Advanced RDS and back?  
I have this problem too, but it is always solved by going into menu and back out, or by going into advanced rds and back.
I demonstrate this in the video from around 0:36

I helped a friend set it up yesterday and he has an older version of V2.0 beta that is 3-4 weeks old. And everything seemed fine with him as well.

**Comment by andimik** [comment]
Oh, thank you for the hint with the advanced RDS view. Will try it later at home.

In your video it was not clear **why** you were doing that.

**Comment by Overland-DX** [comment]
Another thing, If I don't define the StationList ID in TEF6686, then it will only show TEF_tuner in the app.

Yes, the video was actually directed at another group where I was just going to demonstrate the app JB's StatonList-M.

Hope it works for you! :)
This app is a useful tool both with and without TEF :)

**Comment by andimik** [comment]
> Another thing, If I don't define the StationList ID in TEF6686, then it will only show TEF_tuner in the app.

Bingo.

**Comment by Overland-DX** [comment]
> Bingo.

Which doesn't matter, because it works anyway.
It is only to identify tuners if you have several tuners in the same network.

**Comment by PE5PVB** [comment]
I fixed the problem where not always the stationlist ID is send.

**Comment by Overland-DX** [comment]
> I fixed the problem where not always the stationlist ID is send.

Thanks, will test it as soon as it's uploaded :)

**Comment by Overland-DX** [comment]
Unfortunately, that didn't fix the problem. but seems like the problem might as well be in the app.
Because when I tap the box. disable/enabled, then it works as normal again.
![tap](https://github.com/PE5PVB/TEF6686_ESP32/assets/102610897/7aef617f-85b5-4217-861f-fb278b4d1695)

I misunderstood sorry. The Station List ID starts at the ID that is set now.
Have a nice holiday! :)

**Comment by andimik** [comment]
Progress!!

The problem is **nearly** understood, but still needs to be fixed in the source code as it is still buggy.

As I first have used `192.168.43.1` (which I supposed to be my mobile's address), only **some** messages were sent to this IP address (although I thought the TEF will answer to that address) but then I realized (thanks to the app **termux** and `ifconfig` command) that the IP address is `192.168.43.5` in fact. 

So I have changed it to `192.168.43.5` in the menu and now it works from TEF to Stationlist-M. 

But as soon as I change the frequency in Stationlist-M, TEF loses the connection and I have to untick the checkbox and tick it again.

So my suggestions:

- TEF should answer to the Stationlist IP address
- then you could remove the client IP in the menu
- check why a bi-directional connection will then break the communication

**Comment by PE5PVB** [comment]
Well, as explained before. It's just raw UDP traffic, so no handshake or whatever.

**Comment by andimik** [comment]
But could you tell me why some messages (those from my capture) were sent and received, although the IP address was wrong?

**Comment by PE5PVB** [comment]
I have no idea. Try to lock the MAC address of your phone to a fixed IP in your DHCP server.

**Comment by andimik** [comment]
https://android.stackexchange.com/questions/46499/how-configure-the-dhcp-settings-of-wifi-tethering-hotspot-on-android

Your suggestion is not that easy, but I will try to print the IP address for each UDP transmission over USB using `serial.print` commands.

The problem is that each time the Hotspot is enabled it will be assigned another IP address.

I need to find out why some UDP messages were sent **as answer** (the right, but unknown one) to Stationlist and other messages **obviously** (!) used the IP address which was defined in the TEF menu (the wrong one).

**Comment by andimik** [comment]
Dear Sjef, 

**I found the root cause**. 

There were **too many** udp packets sent within a second. I have massively reduced them in my debug version (attached below as ZIP-file), now *Stationlist-M for Android* will update the frequencies in all my tests ...

# :tada: 

So I was **not** a firewall issue. I really believed *Stationlist-M* was ignoring some UDP packets or the connection has been closed due to unknown reasons.

# checking udp-traffic

First I've created a debug version with the following patch:

[tef_stationlist.patch.txt](https://github.com/PE5PVB/TEF6686_ESP32/files/12445422/tef_stationlist.patch.txt)

Then I have connected (your) v1 *TEF* to the USB port (`/dev/ttyUSB`) and have set the *Stationlist-M* IP address of my *mobile* in *TEF*'s menu.

Then I've installed this app on my *mobile*:
![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/b6ea7cdc-c998-4ed6-bf5a-6daf00296ec0)

https://play.google.com/store/apps/details?id=com.sandersoft.udpmonitor&hl=en_US

I could see all the traffic sent to the *mobile* (also when changing the frequency on TEF). So from *TEF*-point all was ok.

[udptraffic.txt](https://github.com/PE5PVB/TEF6686_ESP32/files/12445426/udptraffic.txt)

For example 

```
from=TEF_tuner 1;RcvLevel=27
from=TEF_tuner 1;RcvLevel=27;bandwidth=-1;freq=101100000
from=TEF_tuner 1;PTY=20
[...]
from=TEF_tuner 1;PI=5293
from=TEF_tuner 1;bandwidth=236000
from=TEF_tuner 1;RcvLevel=34
```

And then I've checked the built-in serial monitor in *Arduino IDE*:

```
15:27:19.240 -> remoteip: 192.168.43.105; line 2203 with freq/bw/rcv (FM) 87700 kHz sent  <- changed by SL-M 
15:27:20.916 -> remoteip: 192.168.43.105; line 2203 with freq/bw/rcv (FM) 87800 kHz sent  <- changed by SL-M
15:27:25.524 -> remoteip: 192.168.43.105; line 2203 with freq/bw/rcv (FM) 87900 kHz sent  <- changed by TEF
15:27:26.843 -> remoteip: 192.168.43.105; line 2203 with freq/bw/rcv (FM) 88000 kHz sent  <- changed by TEF
15:27:28.035 -> remoteip: 192.168.43.105; line 2203 with freq/bw/rcv (FM) 88100 kHz sent  <- changed by TEF
```

So basically the IP address was correct (last week I feared that the remoteip address could be wrong). But *SL-M* did **not** update the frequency to 87.9 MHz (= that's why I've opened that issue).

**The hint just activing the advanced RDS view lets *SL-M* update the frequency. Then I had an idea!** 

# :bulb: 

At this moment the udp traffic **pauses** for a short break and starts then again when advanced RDS view is shown on the *TEF*.

# reading the "spec"

That led me to the conclusion that the update speed **might be too much** as his spec says,

>  Refresh rate: not faster than 5x per second.

# counting the messages

I checked, around 70 messages received in one second (I've picked one example and cropped the lines to only one second thanks to the built-in timestamp of the above mentioned *Android* app).

```
$ more /tmp/udp_traffic_1sec.txt | sort | uniq -c
      1 
     70 08/26/2023 04:49:10 /local <-- 192.168.43.209:9031
      1 from=TEF_tuner 1;bandwidth=184000
      2 from=TEF_tuner 1;RcvLevel=32
      4 from=TEF_tuner 1;RcvLevel=33
      5 from=TEF_tuner 1;RcvLevel=34
     22 from=TEF_tuner 1;RcvLevel=35
      1 from=TEF_tuner 1;RcvLevel=36
     35 from=TEF_tuner 1;RT1=536f6c745f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f
```
[udp_traffic_1sec.txt](https://github.com/PE5PVB/TEF6686_ESP32/files/12445605/udp_traffic_1sec.txt)

meaning:

35 times the same RT message (which has not changed) in a second
34 times the RcvLevel status message per second.
Bandwidth only one time.

# proposal and conclusion:

So, my question to you:

**Can we massively decrease the messages and avoid multiple times identical ones?**

BTW: I found another bug regarding ECC and AF (no "from"-address defined) and have sent a PR in the meantime.

# download

This is the compiled debug version for SL-M and serial.print:

# :point_down: 

[TEF6686_ESP32_less_msg.zip](https://github.com/PE5PVB/TEF6686_ESP32/files/12445806/TEF6686_ESP32_less_msg.zip)

**Comment by PE5PVB** [comment]
Most traffic was from signalstrength. I reduced the UDP traffic from the signalstrength to max one message per 2 seconds.

**Comment by andimik** [comment]
Fine, I will test it in the next days. Many thanks for your patience, BTW.

**Comment by andimik** [comment]
I confirm it now works! Therefore, I'll close it.
