### ISSUE TITLE
PI-Code with "show PI-errors" = on

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#376]
If the setting "show PI errors" is switched on, it often happens that the PI-code "shivers". It looks like primary and either secondary or black colour toggle very fast. It remains even if RDS-reception gets lost. This happens typically in case of poor reception.

Also it seems that the questionmarks are not cleared when an uncertain reception lasted a few seconds (and even if RDS-reception gets better later).

**Comment by PE5PVB** [comment]
Fixed.

**Comment by PE5PVB** [comment]
@lxsxl Please confirm and close.

**Comment by lxsxl** [comment]
At least the PI-code won't get stuck anymore. But the "shivering" is still occuring, typically near the threshold between "no RDS" and "RDS available". Maybe this is intended? As a further step to one or two questionmarks?

**Comment by PE5PVB** [comment]
I guess the radio is switching so fast between ? and ?? that it looks like shivering. It rewrites the whole PI with questionmarks, because it can't know the exact x-offset because the fontwidth is different per character.

**Comment by lxsxl** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/af2e137d-04ba-4a0a-90c8-89eee7e1cee6

Maybe this makes it a bit clearer

**Comment by PE5PVB** [comment]
Can you try this again with RDS buffer on?

**Comment by lxsxl** [comment]
What is „RDS buffer“? I tried with „RT buffer“ on but it‘s the same behaviour.

**Comment by PE5PVB** [comment]
When switched off the rds blocks are send from TEF chip without any kind of sync. You can see the effect on the error leds, they will flash very quick after a tune. 

Pro: very vast RDS decoding after tuning
Con: Sync issue, see your video ;-)

**Comment by lxsxl** [comment]
Okay, but which setting do I have to adjust? Or is it within „RT buffer“?

**Comment by PE5PVB** [comment]
RT Buffer is something different. This buffers for example RT A and pushes it when RT B becomes active, and so on. This will prvent showing you a building RT

**Comment by lxsxl** [comment]
Okay. But what is „RDS“? I don‘t find it in the menu. Or is it „RDS filter“?

**Comment by PE5PVB** [comment]
Yes. Sorry

**Comment by lxsxl** [comment]
It is still the same.

**Comment by PE5PVB** [comment]
I added an extra check, hopefully it is better now. Still, during PI scan in error mode it can be set to different values. This goes very quick and for you it looks like it's flashing.

**Comment by lxsxl** [comment]
Actually it seems to be fine, I couldn't see any flashing. So I close this issue.
