### ISSUE TITLE
Bug in memory storage in AM mode

### ISSUE THREAD

**Issue by Overland-DX** [PE5PVB/TEF6686_ESP32#561]
There is a bug in memory storage in AM mode.
When browsing the memory slots you have saved, all memory channels in AM are set to the last frequency you tuned in the relevant AM band.

Version 2.00.16 #548 seems fine, but #550 doesn't work.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by Overland-DX** [comment]
Thanks, but it still doesn't work. Now the frequency is displayed as it should be, but it doesn't exactly tune to the right frequency. Try saving two different stations in SW and you'll see.

**Comment by PE5PVB** [comment]
You are right. Please try again.

**Comment by Overland-DX** [comment]
Now it works fine. Thanks :)
