### ISSUE TITLE
2.11.13: Config wifi connection

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#690]
1. Go to the config wifi connection
Result:
a) the texts are overlapped with the new touch options
b) that menu is a trap... I cannot close it in any way. Just by switching off the radio the user can exit.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/e87fd97b759dd963aef066c4a64e0a60c8dd5c0b

**Comment by numerci** [comment]
Well... partially fixed.
a) fixed and there is no overlapping text
b) despite the new message stating to press Mode to exit the screen when the Mode button is pressed nothing happens. The menu is still a trap in 2.11.14

**Comment by PE5PVB** [comment]
Yeah, it's not possible to exit wifi config. Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/8e98af5a705398af340fa512e8c938bdea338c63

**Comment by numerci** [comment]
Unfortunately, there is no change for this in 2.11.15. Still no way to close the message unless the radio is switched off.

**Comment by PE5PVB** [comment]
Again. You can't escape the WiFi configuration. Only after a succesfull configuration OR a reboot. This is just how the current library works.

**Comment by numerci** [comment]
Ah, sorry I have misunderstood that it was fixed as there was a change and the fix commit. Closed.
