### ISSUE TITLE
Touch events: BW selector not working in RDS Advanced screen

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#700]
In the RDS Advanced screen when pressing in the BW area of the screen it takes the user back to the Main screen. 
Expected to work the same way as the Mono/Stereo switch which works the same way in the Main Screen and RDS Advanced screen,

**Comment by numerci** [comment]
Note: it seem to work fine in the AF screen. So only in the RDS Advanced is not working.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/1383d806261f90f4f57213f688109370fdba601c

**Comment by numerci** [comment]
It works on 2.11.15 but I still have some doubts about some scenarios. However those will be handled by new issues. This one is closed.
